---
title: "dos_graficos_en_uno"
author: "Christian Castro"
date: "19-05-2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE
)
```
</br>

</br>
</br>
</br>
```{r, echo=FALSE}
library(janitor)
library(dplyr)
library(readxl)
covid19 <-
  read_xlsx(
    "C:/Users/usuario/Documents/GitHub/Analisis_covid19_con_R/SIR_19_mayo_graficas/covid19cc.xlsx"
  )
covid19cod_comun <-
  read_xlsx(
    "C:/Users/usuario/Documents/GitHub/Analisis_covid19_con_R/SIR_19_mayo_graficas/covid19ccc.xlsx"
  )

seq <- c(1:280)
vec <- 0
for (i in seq)
{
  # Se selecciona un subset:
  comuna_en_cuestion = covid19[covid19$Codigo_comuna == covid19cod_comun$codigo[i], ]
  
  comuna_en_cuestion$Fecha <-
    excel_numeric_to_date(comuna_en_cuestion$Fecha)
  tabla.comuna = data.frame(comuna_en_cuestion)
  #  j = length(tabla.comuna)+1
  
 # pop_santiago <- 191468
  
  pop_santiago <- covid19cod_comun$poblacion[i]
  
  # Calculamos los infectados, los recuperados y los susceptibles por dias:
  infectados.por.dia = aggregate(tabla.comuna$Casos_Diarios ~ tabla.comuna$Fecha, FUN =
                                   sum)
  recuperados.por.dia = aggregate(tabla.comuna$Recuperados_Diarios ~
                                    tabla.comuna$Fecha, FUN = sum)
  tabla.santiago = data.frame(comuna_en_cuestion$Fecha,
                              infectados.por.dia,
                              recuperados.por.dia)
  tabla.santiago <-
    tabla.santiago %>% mutate(suma_rec_inf = cumsum(
      tabla.comuna.Casos_Diarios + tabla.comuna.Recuperados_Diarios
    ))
  tabla.santiago <-
    tabla.santiago %>% mutate(
      susceptibles = pop_santiago - cumsum(
        tabla.comuna.Casos_Diarios + tabla.comuna.Recuperados_Diarios
      )
    )
  x = tabla.santiago$tabla.comuna.Recuperados_Diarios
  y = pop_santiago * log(tabla.santiago$susceptibles)
  # # summary(lm(y~x))
  # #
  estimacion.R0 = -summary(lm(y ~ x))$coefficients[2]
  
  cod <- covid19cod_comun$codigo[i]
  com <- covid19cod_comun$comuna[i]
  
  # estimacion.R0
  
  i = i + 1
  
  # print(estimacion.R0)
  # print(covid19$Comuna[i])
  
  # cat("El Número Básico de Reproducción para la comuna de",
  #     com,
  #     "es",
  #     estimacion.R0,
  #     "\n")
  
  cat(com,estimacion.R0,"\n")
  
  ## Setup up coordinate system (with x == y aspect ratio):
  # plot(
  #   c(-3, 3),
  #   c(-10, 10),
  #   type = "n",
  #   xlab = "x",
  #   ylab = "y",
  #   asp = 1
  # )
  # ## the x- and y-axis, and an integer grid
  # abline(h = 0, v = 0, col = "gray60")
  # text(1, 0, "( R0 = 0 )", col = "gray60", adj = c(0,-.1))
  # abline(
  #   h = -1:5,
  #   v = -2:3,
  #   col = "lightgray",
  #   lty = 3
  # )
  # abline(a = 0, b = estimacion.R0, col = 2)
  # text(1, 3, "R0", col = 2, adj = c(-.1,-.1))
}

# Gráficas:
# ```{r}
# Setup up coordinate system (with x == y aspect ratio):
# plot(
#   c(-3, 3),
#   c(-10, 10),
#   type = "n",
#   xlab = "x",
#   ylab = "y",
#   asp = 1
# )
# ## the x- and y-axis, and an integer grid
# abline(h = 0, v = 0, col = "gray60")
# text(1, 0, "abline( h = 0 )", col = "gray60", adj = c(0,-.1))
# abline(
#   h = -1:5,
#   v = -2:3,
#   col = "lightgray",
#   lty = 3
# )
# abline(a = 0, b = 0.85656565, col = 2)
# text(1, 3, "abline( 1, 2 )", col = 2, adj = c(-.1,-.1))
# ```



```


