---
title: "analisis_11_mayo"
author: "Christian Castro"
date: "11-05-2020"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### https://rpubs.com/gaston/dendrograms
#### https://www.storybench.org/how-to-use-hierarchical-cluster-analysis-on-time-series-data/
#### R 

```{r, echo=FALSE}

# las dos lineas siguientes impiden el despliegue de advertencias en forma local:
defaultW <- getOption("warn") 
options(warn = -1)

library(tidyverse)
library(gghighlight)
library(magrittr)
library(readxl)
library(readr)
library(ape)
library(ggdendro)

################################################

covid19_x1 <- read_csv2("C:/Users/usuario/Documents/GitHub/Analisis_covid19_con_R/analisis_11_mayo/covid19_x3.csv")

#covid19_x1$Fecha %<>% as.Date(format="%d/%m/%y")

head(covid19_x1, n=10)
str(covid19_x1)
summary(covid19_x1)

ggplot(covid19_x1, aes(Fec, Casos_Acumulados, color=Comuna))+
    geom_line(stat="identity")  +
    ylab("Casos_Acumulados") +
    gghighlight(max(Casos_Acumulados) > 600,
        max_highlight = 1,
        use_direct_label = TRUE) +
        theme_minimal() +
        theme(legend.position = 'none')

#########################################



#########################################

# Despliegue del primer dendograma, pero primero hagamos un wrangling a los datos:

Casos_Acumulados <- covid19_x1 %>%
  select(Casos_Acumulados, Fec, Comuna) %>%
  drop_na() %>% # must drop NAs for clustering to work
  glimpse()

spread_homs_per_100k <- Casos_Acumulados %>%
  spread(Comuna,  Casos_Acumulados)  %>%
  glimpse()

murders <- t(spread_homs_per_100k[-1])
Casos_Acumulados <- dist(murders, method="euclidean")  
fit <- hclust(Casos_Acumulados, method="ward.D")  

png("dendrograma.png",width=6000,height=2400)
par(cex=1,font=1)
plot(fit, family="Arial",  main="Dendrograma de los casos acumulados de Covid19 en las comunas de Chile, agrupados en 5 clusters, del 3 de Marzo al 10 de Mayo del 2020")
# Construimos 5 clusters
x<- rect.hclust(fit, k=5, border="red")
x
dev.off()

par(cex=0.5,font=1)
plot(fit, family="Arial",  main="Dendrograma de los casos acumulados de Covid19 en las comunas de Chile, agrupados en 5 clusters, del 3 de Marzo al 10 de Mayo del 2020")
x<- rect.hclust(fit, k=5, border="red")

#########################################
# Dendrograma en forma circular:

png("dendrograma_circular.png",width=6000,height=2400)
par(cex=1,font=2)
colors = c("red", "blue", "green", "black", "violet")
clus4 = cutree(fit, 5)
plot(as.phylo(fit), type = "fan",  main="Dendrograma circular de los casos acumulados de Covid19 en las comunas de Chile, agrupados en 4 clusters,  del 3 de Marzo al 10 de Mayo del 2020", tip.color = colors[clus4], label.offset = 30, cex = 1.3)
dev.off()


par(cex=0.5,font=1)
colors = c("red", "blue", "green", "black", "violet")
clus4 = cutree(fit, 5)
plot(as.phylo(fit), type = "fan",  main="Dendrograma circular de los casos acumulados de Covid19 en las comunas de Chile, agrupados en 4 clusters,  del 3 de Marzo al 10 de Mayo del 2020", tip.color = colors[clus4], label.offset = 300, cex = 0.6)


#########################################

#Visualiza todas las ciudades que pertenecen a un grupo

ggdendrogram(fit, rotate = TRUE,  size = 8,  theme_dendro = FALSE) +
  theme_minimal() + xlab("") + ylab("")

#########################################
# Distancia euclidea aplicada sobre todo el set de datos:

dist <- dist(covid19_x1[ , c(7:9)] , diag=TRUE)
hc <- hclust(dist)
png("dendrograma_total.png",width=6000,height=2400)
par(cex=1,font=1)
plot(hc)
dev.off()

#########################################

clustered_data <- cutree(fit, k=5)
clustered_data_tidy <- as.data.frame(as.table(clustered_data)) %>% glimpse()

colnames(clustered_data_tidy) <- c("Comuna","cluster")

clustered_data_tidy$Comuna <- as.character(clustered_data_tidy$Comuna)

joined_clusters <- covid19_x1 %>%
  inner_join(clustered_data_tidy, by = "Comuna") %>%
  glimpse()

table(clustered_data_tidy$cluster)

cluster3 <- joined_clusters %>% filter(cluster == "5") 
ggplot(cluster3, aes(Fec, Casos_Acumulados)) +
  geom_line(color="grey") +
  theme_minimal() +
  ylab("Casos_Acumulados") + xlab("") +
  geom_smooth(method="auto",color="red", se=F, size=1) +
  facet_wrap(~Comuna)
#################################
#Analisis de los casos diarios:

ggplot(covid19_x1, aes(Fec, Casos_Activos, color=Comuna))+
    geom_line(stat="identity")  +
    ylab("Casos_Activos") +
    gghighlight(max(Casos_Activos) > 300,
        max_highlight = 1,
        use_direct_label = TRUE) +
        theme_minimal() +
        theme(legend.position = 'none')

```
